name: Desktop Build
on: [push, pull_request]

jobs:
    build-win:
        name: Build for Windows
        runs-on: windows-latest
        strategy:
          fail-fast: false
          matrix:
              arch: [x64, ARM64]
              target: [Windows]

        steps:
          - uses: actions/checkout@v4
          - name: Configure
            run: cmake -B build -DCMAKE_SYSTEM_NAME=${{ matrix.target }} -DCMAKE_SYSTEM_VERSION="10.0" -A ${{ matrix.arch }}
          - name: Build
            run: cmake --build build --target miskeenity-canvas --config MinSizeRel --parallel && cmake --install build --config MinSizeRel
          - name: Upload Build
            uses: actions/upload-artifact@v4
            with: 
                name: miskeenity-canvas-${{ matrix.target }}-${{ matrix.arch }}
                path: build/bin/*
    build-mac:
        name: Build for Apple
        runs-on: macos-14
        strategy:
          fail-fast: false
          matrix:
              target: [Darwin]

        steps:
          - uses: actions/checkout@v4
            with:
                submodules: recursive
          - name: Setup Xcode version
            uses: maxim-lobanov/setup-xcode@v1.6.0
            with:
                xcode-version: "16.1"
          - name: Configure
            run: cmake -G "Xcode" -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED=NO -DCMAKE_SYSTEM_NAME=${{ matrix.target }} -DSDL_STATIC=ON -DSDL_SHARED=OFF -S . -B build
          - name: Build
            run: cmake --build build --target miskeenity-canvas --config MinSizeRel --parallel && cmake --install build --config MinSizeRel
          - name: Upload Build
            uses: actions/upload-artifact@v4
            with: 
                name: miskeenity-canvas-${{ matrix.target }}
                path: build/bin/*