name: Desktop Build
on: [push, pull_request]

jobs:
    build-win:
        name: Build for Windows
        runs-on: windows-latest
        strategy:
          fail-fast: false
          matrix:
              arch: [x64, ARM64]
              target: [Windows]

        steps:
          - uses: actions/checkout@v4
          - name: Configure
            run: cmake -B build -DCMAKE_SYSTEM_NAME=${{ matrix.target }} -DCMAKE_SYSTEM_VERSION="10.0" -A${{ matrix.arch }}
          - name: Build
            run: cmake --build build --target miskeenity-canvas --config MinSizeRel --parallel
          - name: Upload Build
            uses: actions/upload-artifact@v4
            with: 
                name: miskeenity-canvas-${{ matrix.target }}-${{ matrix.arch }}
                path: |
                    build/MinSizeRel/*.exe
