name: Desktop Build
on: [push, pull_request]

jobs:
    build-win:
        name: Build for Windows
        runs-on: windows-latest
        strategy:
          fail-fast: false
          matrix:
              arch: [x64, ARM64]
              target: [Windows]

        steps:
          - uses: actions/checkout@v4
          - name: Configure
            run: cmake -B build -DCMAKE_SYSTEM_NAME=${{ matrix.target }} -DCMAKE_SYSTEM_VERSION="10.0"  -DCMAKE_BUILD_TYPE=MinSizeRel -A ${{ matrix.arch }}
          - name: Build
            run: cmake --build build --target miskeenity-canvas --config MinSizeRel --parallel && cmake --install build --config MinSizeRel --component miskeenity-canvas
          - name: Upload Build
            uses: actions/upload-artifact@v4
            with: 
                name: miskeenity-canvas-${{ matrix.target }}-${{ matrix.arch }}
                path: build/bin/*
    build-mac:
        name: Build for Apple
        runs-on: macos-14
        strategy:
          fail-fast: false
          matrix:
            arch: [arm64]
            target: [Darwin]

        steps:
          - uses: actions/checkout@v4
            with:
                submodules: recursive
          - name: Setup Ninja
            uses: seanmiddleditch/gha-setup-ninja@master
          - name: Configure
            run: cmake -G Ninja -DCMAKE_SYSTEM_NAME=${{ matrix.target }}  -DCMAKE_BUILD_TYPE=MinSizeRel -S . -B build
          - name: Build
            run: cmake --build build --target miskeenity-canvas --config MinSizeRel --parallel && cmake --install build --config MinSizeRel --component miskeenity-canvas
          - name: Upload Build
            uses: actions/upload-artifact@v4
            with: 
                name: miskeenity-canvas-${{ matrix.target }}-${{ matrix.arch }}
                path: build/bin/*